#!/usr/bin/python3
def raise_exception_msg(message=""):
    name = "Sanni"
    print(message)
